version: '3.1'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./php/src:/var/www/html/

  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: people
      MYSQL_USER: people
      MYSQL_PASSWORD: people

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '28080:80'
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: people
      PMA_PASSWORD: people
      UPLOAD_LIMIT: 256M
    depends_on:
      - db
